name: gua_flutter_h5webview
description: 用于学习 flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  # 图标
  cupertino_icons: 1.0.2 # 图标 iOS 风格

  # 状态
  get: 4.6.6 #状态管理

  # 框架、工具
  flutter_screenutil: 5.9.0 # 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil/blob/master/README_CN.md
  logger: 2.0.2 #日志 https://github.com/SourceHorizon/logger
  
  # Widget
  flutter_easyloading: 3.0.5 # loading/toast https://github.com/nslogx/flutter_easyloading/blob/develop/README-zh_CN.md
  flutter_inappwebview: 6.0.0 # webview flutter 中加载网页 https://inappwebview.dev/

  #系统交互
  path_provider: 2.0.13 # 获取路径相关
  permission_handler: 11.2.0 #权限处理

  url_launcher: 6.2.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/img/
    - assets/img/colorful/
    - assets/img/colorful/icon/
    - assets/img/colorful/抽卡/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
